# Generated by Django 3.0.3 on 2020-09-04 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=30)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('vendor', models.CharField(max_length=20)),
                ('purchaser', models.CharField(max_length=20)),
                ('invoicenumber', models.IntegerField(primary_key=True, serialize=False)),
                ('duedate', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.FloatField()),
                ('tax', models.FloatField()),
                ('total', models.FloatField()),
                ('items', models.ManyToManyField(to='invoiceManageApp.Item')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file', models.FileField(upload_to='')),
                ('custname', models.CharField(default='admin', max_length=10)),
                ('filename', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('uploadedtime', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoiceManageApp.Invoice')),
            ],
        ),
    ]
